FROM tiangolo/uvicorn-gunicorn-fastapi:python3.11-slim 
RUN mkdir -p /usr/app/backend
WORKDIR /usr/app/backend
COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY ./src .

ENV PYTHONPATH=/usr/app/backend
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host=0.0.0.0" , "--reload" , "--port", "8000"]